### ISSUE TITLE
Download the board configuration information from Google sheet

### ISSUE THREAD

**Issue by mithro** [CarlFK/pici#28]
The Google Sheet @ 
https://docs.google.com/spreadsheets/d/1CY38U9o4KPCZvfdblJWgpEBKLCnMhlQipjTqfH6QVOw/edit?gid=0#gid=0 has the information about names / mac addresses / etc.

**Comment by mithro** [comment]
Can ansible import data from a CSV file?

**Comment by mithro** [comment]
https://docs.ansible.com/ansible/latest/collections/community/general/read_csv_module.html

**Comment by CarlFK** [comment]
I could be convinced, but currently this seems like too much work. 

csv is much less human readable vs ansible inventory yaml.  goog sheet ui is nice, but it adds a layer of abstraction or something to the data ansible needs to consume. 

80% of the time spent on this project is R&D.  during this part, everything is dynamic - the physical setup and the configs describing it, and the process (ansible) that use it.    I feel like relying on the goog sheet adds complexity for a net loss. 
 
a part of the R&D is changing the "data schema" - like currently a PIs IP is derived from the switch port number it is plugged into (port 3 gets x.y.z.103) i can see this changing and relying on data.  There is currently one pi designated "management pi"  and its IP is hardcoded into data somewhere, breaking normalization/DRY.   this might go away once management happens with qemu.


wget above needs -O out.csv (not -o)

veyepar import addeps - my collection of consumers

```
>>> rows = addeps.csv_sheet("out.csv")
>>> rows[0]
{'Port': '1', 'Site': 'welland', 'Name': 'pi1.welland.fpgas.mithis.com', 'SSH Port': '10122', 'IP': '10.21.0.101', 'Column 19': '10.21.0.101', 'Uplink MAC': '', 'FPGA MAC': '', 'WLAN MAC': '', 'Arty MAC': '', 'Serial No': '', 'Cable Color': '', 'Location': '', 'RPi Model': '', 'Hat': '', 'Arty Serial': '', 'Arty FPGA': '', 'Arty Memory': '', 'Arty SPI Flash': ''}
```
'Column 19'  ?

If I was going to use the goog sheet, I would rather use the API even if it more work short term, I have hope that it pays off over time.  


>>> addeps.goog_sheet("1CY38U9o4KPCZvfdblJWgpEBKLCnMhlQipjTqfH6QVOw")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/carl/src/veyepar/dj/scripts/addeps.py", line 249, in goog_sheet
    creds.refresh(Request())
  File "/home/carl/.virtualenvs/veyepar/lib/python3.12/site-packages/google/oauth2/credentials.py", line 412, in refresh
    ) = reauth.refresh_grant(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/carl/.virtualenvs/veyepar/lib/python3.12/site-packages/google/oauth2/reauth.py", line 370, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/home/carl/.virtualenvs/veyepar/lib/python3.12/site-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
